import BibTeXFormat.BST: Identifier, FunctionLiteral, QuotedVar,
                         BSTString, BSTInteger

bst = [["ENTRY",
  [Identifier("address"),
   Identifier("author"),
   Identifier("booktitle"),
   Identifier("chapter"),
   Identifier("edition"),
   Identifier("editor"),
   Identifier("howpublished"),
   Identifier("institution"),
   Identifier("journal"),
   Identifier("key"),
   Identifier("month"),
   Identifier("note"),
   Identifier("number"),
   Identifier("organization"),
   Identifier("pages"),
   Identifier("publisher"),
   Identifier("school"),
   Identifier("series"),
   Identifier("title"),
   Identifier("type"),
   Identifier("volume"),
   Identifier("year")],
  [],
  [Identifier("label")]],
 ["INTEGERS",
  [Identifier("output.state"),
   Identifier("before.all"),
   Identifier("mid.sentence"),
   Identifier("after.sentence"),
   Identifier("after.block")]],
 ["FUNCTION",
  [Identifier("init.state.consts")],
  [BSTInteger(0),
   QuotedVar("before.all"),
   Identifier(":="),
   BSTInteger(1),
   QuotedVar("mid.sentence"),
   Identifier(":="),
   BSTInteger(2),
   QuotedVar("after.sentence"),
   Identifier(":="),
   BSTInteger(3),
   QuotedVar("after.block"),
   Identifier(":=")]],
 ["STRINGS", [Identifier("s"), Identifier("t")]],
 ["FUNCTION",
  [Identifier("output.nonnull")],
  [QuotedVar("s"),
   Identifier(":="),
   Identifier("output.state"),
   Identifier("mid.sentence"),
   Identifier("="),
   FunctionLiteral([BSTString(", "), Identifier("*"), Identifier("write\$")]),
   FunctionLiteral([Identifier("output.state"), Identifier("after.block"), Identifier("="), FunctionLiteral([Identifier("add.period\$"), Identifier("write\$"), Identifier("newline\$"), BSTString("\\newblock "), Identifier("write\$")]), FunctionLiteral([Identifier("output.state"), Identifier("before.all"), Identifier("="), QuotedVar("write\$"), FunctionLiteral([Identifier("add.period\$"), BSTString(" "), Identifier("*"), Identifier("write\$")]), Identifier("if\$")]), Identifier("if\$"), Identifier("mid.sentence"), QuotedVar("output.state"), Identifier(":=")]),
   Identifier("if\$"),
   Identifier("s")]],
 ["FUNCTION",
  [Identifier("output")],
  [Identifier("duplicate\$"),
   Identifier("empty\$"),
   QuotedVar("pop\$"),
   QuotedVar("output.nonnull"),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("output.check")],
  [QuotedVar("t"),
   Identifier(":="),
   Identifier("duplicate\$"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("pop\$"), BSTString("empty "), Identifier("t"), Identifier("*"), BSTString(" in "), Identifier("*"), Identifier("cite\$"), Identifier("*"), Identifier("warning\$")]),
   QuotedVar("output.nonnull"),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("output.bibitem")],
  [Identifier("newline\$"),
   BSTString("\\bibitem{"),
   Identifier("write\$"),
   Identifier("cite\$"),
   Identifier("write\$"),
   BSTString("}"),
   Identifier("write\$"),
   Identifier("newline\$"),
   BSTString(""),
   Identifier("before.all"),
   QuotedVar("output.state"),
   Identifier(":=")]],
 ["FUNCTION",
  [Identifier("fin.entry")],
  [Identifier("add.period\$"),
   Identifier("write\$"),
   Identifier("newline\$")]],
 ["FUNCTION",
  [Identifier("new.block")],
  [Identifier("output.state"),
   Identifier("before.all"),
   Identifier("="),
   QuotedVar("skip\$"),
   FunctionLiteral([Identifier("after.block"), QuotedVar("output.state"), Identifier(":=")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("new.sentence")],
  [Identifier("output.state"),
   Identifier("after.block"),
   Identifier("="),
   QuotedVar("skip\$"),
   FunctionLiteral([Identifier("output.state"), Identifier("before.all"), Identifier("="), QuotedVar("skip\$"), FunctionLiteral([Identifier("after.sentence"), QuotedVar("output.state"), Identifier(":=")]), Identifier("if\$")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("not")],
  [FunctionLiteral([BSTInteger(0)]),
   FunctionLiteral([BSTInteger(1)]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("and")],
  [QuotedVar("skip\$"),
   FunctionLiteral([Identifier("pop\$"), BSTInteger(0)]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("or")],
  [FunctionLiteral([Identifier("pop\$"), BSTInteger(1)]),
   QuotedVar("skip\$"),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("new.block.checka")],
  [Identifier("empty\$"),
   QuotedVar("skip\$"),
   QuotedVar("new.block"),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("new.block.checkb")],
  [Identifier("empty\$"),
   Identifier("swap\$"),
   Identifier("empty\$"),
   Identifier("and"),
   QuotedVar("skip\$"),
   QuotedVar("new.block"),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("new.sentence.checka")],
  [Identifier("empty\$"),
   QuotedVar("skip\$"),
   QuotedVar("new.sentence"),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("new.sentence.checkb")],
  [Identifier("empty\$"),
   Identifier("swap\$"),
   Identifier("empty\$"),
   Identifier("and"),
   QuotedVar("skip\$"),
   QuotedVar("new.sentence"),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("field.or.null")],
  [Identifier("duplicate\$"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("pop\$"), BSTString("")]),
   QuotedVar("skip\$"),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("emphasize")],
  [Identifier("duplicate\$"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("pop\$"), BSTString("")]),
   FunctionLiteral([BSTString("{\\em "), Identifier("swap\$"), Identifier("*"), BSTString("}"), Identifier("*")]),
   Identifier("if\$")]],
 ["INTEGERS",
  [Identifier("nameptr"), Identifier("namesleft"), Identifier("numnames")]],
 ["FUNCTION",
  [Identifier("format.names")],
  [QuotedVar("s"),
   Identifier(":="),
   BSTInteger(1),
   QuotedVar("nameptr"),
   Identifier(":="),
   Identifier("s"),
   Identifier("num.names\$"),
   QuotedVar("numnames"),
   Identifier(":="),
   Identifier("numnames"),
   QuotedVar("namesleft"),
   Identifier(":="),
   FunctionLiteral([Identifier("namesleft"), BSTInteger(0), Identifier(">")]),
   FunctionLiteral([Identifier("s"), Identifier("nameptr"), BSTString("{ff~}{vv~}{ll}{, jj}"), Identifier("format.name\$"), QuotedVar("t"), Identifier(":="), Identifier("nameptr"), BSTInteger(1), Identifier(">"), FunctionLiteral([Identifier("namesleft"), BSTInteger(1), Identifier(">"), FunctionLiteral([BSTString(", "), Identifier("*"), Identifier("t"), Identifier("*")]), FunctionLiteral([Identifier("numnames"), BSTInteger(2), Identifier(">"), FunctionLiteral([BSTString(","), Identifier("*")]), QuotedVar("skip\$"), Identifier("if\$"), Identifier("t"), BSTString("others"), Identifier("="), FunctionLiteral([BSTString(" et~al."), Identifier("*")]), FunctionLiteral([BSTString(" and "), Identifier("*"), Identifier("t"), Identifier("*")]), Identifier("if\$")]), Identifier("if\$")]), QuotedVar("t"), Identifier("if\$"), Identifier("nameptr"), BSTInteger(1), Identifier("+"), QuotedVar("nameptr"), Identifier(":="), Identifier("namesleft"), BSTInteger(1), Identifier("-"), QuotedVar("namesleft"), Identifier(":=")]),
   Identifier("while\$")]],
 ["FUNCTION",
  [Identifier("format.authors")],
  [Identifier("author"),
   Identifier("empty\$"),
   FunctionLiteral([BSTString("")]),
   FunctionLiteral([Identifier("author"), Identifier("format.names")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("format.editors")],
  [Identifier("editor"),
   Identifier("empty\$"),
   FunctionLiteral([BSTString("")]),
   FunctionLiteral([Identifier("editor"), Identifier("format.names"), Identifier("editor"), Identifier("num.names\$"), BSTInteger(1), Identifier(">"), FunctionLiteral([BSTString(", editors"), Identifier("*")]), FunctionLiteral([BSTString(", editor"), Identifier("*")]), Identifier("if\$")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("format.title")],
  [Identifier("title"),
   Identifier("empty\$"),
   FunctionLiteral([BSTString("")]),
   FunctionLiteral([Identifier("title"), BSTString("t"), Identifier("change.case\$")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("n.dashify")],
  [QuotedVar("t"),
   Identifier(":="),
   BSTString(""),
   FunctionLiteral([Identifier("t"), Identifier("empty\$"), Identifier("not")]),
   FunctionLiteral([Identifier("t"), BSTInteger(1), BSTInteger(1), Identifier("substring\$"), BSTString("-"), Identifier("="), FunctionLiteral([Identifier("t"), BSTInteger(1), BSTInteger(2), Identifier("substring\$"), BSTString("--"), Identifier("="), Identifier("not"), FunctionLiteral([BSTString("--"), Identifier("*"), Identifier("t"), BSTInteger(2), Identifier("global.max\$"), Identifier("substring\$"), QuotedVar("t"), Identifier(":=")]), FunctionLiteral([FunctionLiteral([Identifier("t"), BSTInteger(1), BSTInteger(1), Identifier("substring\$"), BSTString("-"), Identifier("=")]), FunctionLiteral([BSTString("-"), Identifier("*"), Identifier("t"), BSTInteger(2), Identifier("global.max\$"), Identifier("substring\$"), QuotedVar("t"), Identifier(":=")]), Identifier("while\$")]), Identifier("if\$")]), FunctionLiteral([Identifier("t"), BSTInteger(1), BSTInteger(1), Identifier("substring\$"), Identifier("*"), Identifier("t"), BSTInteger(2), Identifier("global.max\$"), Identifier("substring\$"), QuotedVar("t"), Identifier(":=")]), Identifier("if\$")]),
   Identifier("while\$")]],
 ["FUNCTION",
  [Identifier("format.date")],
  [Identifier("year"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("month"), Identifier("empty\$"), FunctionLiteral([BSTString("")]), FunctionLiteral([BSTString("there's a month but no year in "), Identifier("cite\$"), Identifier("*"), Identifier("warning\$"), Identifier("month")]), Identifier("if\$")]),
   FunctionLiteral([Identifier("month"), Identifier("empty\$"), QuotedVar("year"), FunctionLiteral([Identifier("month"), BSTString(" "), Identifier("*"), Identifier("year"), Identifier("*")]), Identifier("if\$")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("format.btitle")],
  [Identifier("title"), Identifier("emphasize")]],
 ["FUNCTION",
  [Identifier("tie.or.space.connect")],
  [Identifier("duplicate\$"),
   Identifier("text.length\$"),
   BSTInteger(3),
   Identifier("<"),
   FunctionLiteral([BSTString("~")]),
   FunctionLiteral([BSTString(" ")]),
   Identifier("if\$"),
   Identifier("swap\$"),
   Identifier("*"),
   Identifier("*")]],
 ["FUNCTION",
  [Identifier("either.or.check")],
  [Identifier("empty\$"),
   QuotedVar("pop\$"),
   FunctionLiteral([BSTString("can't use both "), Identifier("swap\$"), Identifier("*"), BSTString(" fields in "), Identifier("*"), Identifier("cite\$"), Identifier("*"), Identifier("warning\$")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("format.bvolume")],
  [Identifier("volume"),
   Identifier("empty\$"),
   FunctionLiteral([BSTString("")]),
   FunctionLiteral([BSTString("volume"), Identifier("volume"), Identifier("tie.or.space.connect"), Identifier("series"), Identifier("empty\$"), QuotedVar("skip\$"), FunctionLiteral([BSTString(" of "), Identifier("*"), Identifier("series"), Identifier("emphasize"), Identifier("*")]), Identifier("if\$"), BSTString("volume and number"), Identifier("number"), Identifier("either.or.check")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("format.number.series")],
  [Identifier("volume"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("number"), Identifier("empty\$"), FunctionLiteral([Identifier("series"), Identifier("field.or.null")]), FunctionLiteral([Identifier("output.state"), Identifier("mid.sentence"), Identifier("="), FunctionLiteral([BSTString("number")]), FunctionLiteral([BSTString("Number")]), Identifier("if\$"), Identifier("number"), Identifier("tie.or.space.connect"), Identifier("series"), Identifier("empty\$"), FunctionLiteral([BSTString("there's a number but no series in "), Identifier("cite\$"), Identifier("*"), Identifier("warning\$")]), FunctionLiteral([BSTString(" in "), Identifier("*"), Identifier("series"), Identifier("*")]), Identifier("if\$")]), Identifier("if\$")]),
   FunctionLiteral([BSTString("")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("format.edition")],
  [Identifier("edition"),
   Identifier("empty\$"),
   FunctionLiteral([BSTString("")]),
   FunctionLiteral([Identifier("output.state"), Identifier("mid.sentence"), Identifier("="), FunctionLiteral([Identifier("edition"), BSTString("l"), Identifier("change.case\$"), BSTString(" edition"), Identifier("*")]), FunctionLiteral([Identifier("edition"), BSTString("t"), Identifier("change.case\$"), BSTString(" edition"), Identifier("*")]), Identifier("if\$")]),
   Identifier("if\$")]],
 ["INTEGERS", [Identifier("multiresult")]],
 ["FUNCTION",
  [Identifier("multi.page.check")],
  [QuotedVar("t"),
   Identifier(":="),
   BSTInteger(0),
   QuotedVar("multiresult"),
   Identifier(":="),
   FunctionLiteral([Identifier("multiresult"), Identifier("not"), Identifier("t"), Identifier("empty\$"), Identifier("not"), Identifier("and")]),
   FunctionLiteral([Identifier("t"), BSTInteger(1), BSTInteger(1), Identifier("substring\$"), Identifier("duplicate\$"), BSTString("-"), Identifier("="), Identifier("swap\$"), Identifier("duplicate\$"), BSTString(","), Identifier("="), Identifier("swap\$"), BSTString("+"), Identifier("="), Identifier("or"), Identifier("or"), FunctionLiteral([BSTInteger(1), QuotedVar("multiresult"), Identifier(":=")]), FunctionLiteral([Identifier("t"), BSTInteger(2), Identifier("global.max\$"), Identifier("substring\$"), QuotedVar("t"), Identifier(":=")]), Identifier("if\$")]),
   Identifier("while\$"),
   Identifier("multiresult")]],
 ["FUNCTION",
  [Identifier("format.pages")],
  [Identifier("pages"),
   Identifier("empty\$"),
   FunctionLiteral([BSTString("")]),
   FunctionLiteral([Identifier("pages"), Identifier("multi.page.check"), FunctionLiteral([BSTString("pages"), Identifier("pages"), Identifier("n.dashify"), Identifier("tie.or.space.connect")]), FunctionLiteral([BSTString("page"), Identifier("pages"), Identifier("tie.or.space.connect")]), Identifier("if\$")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("format.vol.num.pages")],
  [Identifier("volume"),
   Identifier("field.or.null"),
   Identifier("number"),
   Identifier("empty\$"),
   QuotedVar("skip\$"),
   FunctionLiteral([BSTString("("), Identifier("number"), Identifier("*"), BSTString(")"), Identifier("*"), Identifier("*"), Identifier("volume"), Identifier("empty\$"), FunctionLiteral([BSTString("there's a number but no volume in "), Identifier("cite\$"), Identifier("*"), Identifier("warning\$")]), QuotedVar("skip\$"), Identifier("if\$")]),
   Identifier("if\$"),
   Identifier("pages"),
   Identifier("empty\$"),
   QuotedVar("skip\$"),
   FunctionLiteral([Identifier("duplicate\$"), Identifier("empty\$"), FunctionLiteral([Identifier("pop\$"), Identifier("format.pages")]), FunctionLiteral([BSTString(":"), Identifier("*"), Identifier("pages"), Identifier("n.dashify"), Identifier("*")]), Identifier("if\$")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("format.chapter.pages")],
  [Identifier("chapter"),
   Identifier("empty\$"),
   QuotedVar("format.pages"),
   FunctionLiteral([Identifier("type"), Identifier("empty\$"), FunctionLiteral([BSTString("chapter")]), FunctionLiteral([Identifier("type"), BSTString("l"), Identifier("change.case\$")]), Identifier("if\$"), Identifier("chapter"), Identifier("tie.or.space.connect"), Identifier("pages"), Identifier("empty\$"), QuotedVar("skip\$"), FunctionLiteral([BSTString(", "), Identifier("*"), Identifier("format.pages"), Identifier("*")]), Identifier("if\$")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("format.in.ed.booktitle")],
  [Identifier("booktitle"),
   Identifier("empty\$"),
   FunctionLiteral([BSTString("")]),
   FunctionLiteral([Identifier("editor"), Identifier("empty\$"), FunctionLiteral([BSTString("In "), Identifier("booktitle"), Identifier("emphasize"), Identifier("*")]), FunctionLiteral([BSTString("In "), Identifier("format.editors"), Identifier("*"), BSTString(", "), Identifier("*"), Identifier("booktitle"), Identifier("emphasize"), Identifier("*")]), Identifier("if\$")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("empty.misc.check")],
  [Identifier("author"),
   Identifier("empty\$"),
   Identifier("title"),
   Identifier("empty\$"),
   Identifier("howpublished"),
   Identifier("empty\$"),
   Identifier("month"),
   Identifier("empty\$"),
   Identifier("year"),
   Identifier("empty\$"),
   Identifier("note"),
   Identifier("empty\$"),
   Identifier("and"),
   Identifier("and"),
   Identifier("and"),
   Identifier("and"),
   Identifier("and"),
   Identifier("key"),
   Identifier("empty\$"),
   Identifier("not"),
   Identifier("and"),
   FunctionLiteral([BSTString("all relevant fields are empty in "), Identifier("cite\$"), Identifier("*"), Identifier("warning\$")]),
   QuotedVar("skip\$"),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("format.thesis.type")],
  [Identifier("type"),
   Identifier("empty\$"),
   QuotedVar("skip\$"),
   FunctionLiteral([Identifier("pop\$"), Identifier("type"), BSTString("t"), Identifier("change.case\$")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("format.tr.number")],
  [Identifier("type"),
   Identifier("empty\$"),
   FunctionLiteral([BSTString("Technical Report")]),
   QuotedVar("type"),
   Identifier("if\$"),
   Identifier("number"),
   Identifier("empty\$"),
   FunctionLiteral([BSTString("t"), Identifier("change.case\$")]),
   FunctionLiteral([Identifier("number"), Identifier("tie.or.space.connect")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("format.article.crossref")],
  [Identifier("key"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("journal"), Identifier("empty\$"), FunctionLiteral([BSTString("need key or journal for "), Identifier("cite\$"), Identifier("*"), BSTString(" to crossref "), Identifier("*"), Identifier("crossref"), Identifier("*"), Identifier("warning\$"), BSTString("")]), FunctionLiteral([BSTString("In {\\em "), Identifier("journal"), Identifier("*"), BSTString("\\/}"), Identifier("*")]), Identifier("if\$")]),
   FunctionLiteral([BSTString("In "), Identifier("key"), Identifier("*")]),
   Identifier("if\$"),
   BSTString(" \\cite{"),
   Identifier("*"),
   Identifier("crossref"),
   Identifier("*"),
   BSTString("}"),
   Identifier("*")]],
 ["FUNCTION",
  [Identifier("format.crossref.editor")],
  [Identifier("editor"),
   BSTInteger(1),
   BSTString("{vv~}{ll}"),
   Identifier("format.name\$"),
   Identifier("editor"),
   Identifier("num.names\$"),
   Identifier("duplicate\$"),
   BSTInteger(2),
   Identifier(">"),
   FunctionLiteral([Identifier("pop\$"), BSTString(" et~al."), Identifier("*")]),
   FunctionLiteral([BSTInteger(2), Identifier("<"), QuotedVar("skip\$"), FunctionLiteral([Identifier("editor"), BSTInteger(2), BSTString("{ff }{vv }{ll}{ jj}"), Identifier("format.name\$"), BSTString("others"), Identifier("="), FunctionLiteral([BSTString(" et~al."), Identifier("*")]), FunctionLiteral([BSTString(" and "), Identifier("*"), Identifier("editor"), BSTInteger(2), BSTString("{vv~}{ll}"), Identifier("format.name\$"), Identifier("*")]), Identifier("if\$")]), Identifier("if\$")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("format.book.crossref")],
  [Identifier("volume"),
   Identifier("empty\$"),
   FunctionLiteral([BSTString("empty volume in "), Identifier("cite\$"), Identifier("*"), BSTString("'s crossref of "), Identifier("*"), Identifier("crossref"), Identifier("*"), Identifier("warning\$"), BSTString("In ")]),
   FunctionLiteral([BSTString("Volume"), Identifier("volume"), Identifier("tie.or.space.connect"), BSTString(" of "), Identifier("*")]),
   Identifier("if\$"),
   Identifier("editor"),
   Identifier("empty\$"),
   Identifier("editor"),
   Identifier("field.or.null"),
   Identifier("author"),
   Identifier("field.or.null"),
   Identifier("="),
   Identifier("or"),
   FunctionLiteral([Identifier("key"), Identifier("empty\$"), FunctionLiteral([Identifier("series"), Identifier("empty\$"), FunctionLiteral([BSTString("need editor, key, or series for "), Identifier("cite\$"), Identifier("*"), BSTString(" to crossref "), Identifier("*"), Identifier("crossref"), Identifier("*"), Identifier("warning\$"), BSTString(""), Identifier("*")]), FunctionLiteral([BSTString("{\\em "), Identifier("*"), Identifier("series"), Identifier("*"), BSTString("\\/}"), Identifier("*")]), Identifier("if\$")]), FunctionLiteral([Identifier("key"), Identifier("*")]), Identifier("if\$")]),
   FunctionLiteral([Identifier("format.crossref.editor"), Identifier("*")]),
   Identifier("if\$"),
   BSTString(" \\cite{"),
   Identifier("*"),
   Identifier("crossref"),
   Identifier("*"),
   BSTString("}"),
   Identifier("*")]],
 ["FUNCTION",
  [Identifier("format.incoll.inproc.crossref")],
  [Identifier("editor"),
   Identifier("empty\$"),
   Identifier("editor"),
   Identifier("field.or.null"),
   Identifier("author"),
   Identifier("field.or.null"),
   Identifier("="),
   Identifier("or"),
   FunctionLiteral([Identifier("key"), Identifier("empty\$"), FunctionLiteral([Identifier("booktitle"), Identifier("empty\$"), FunctionLiteral([BSTString("need editor, key, or booktitle for "), Identifier("cite\$"), Identifier("*"), BSTString(" to crossref "), Identifier("*"), Identifier("crossref"), Identifier("*"), Identifier("warning\$"), BSTString("")]), FunctionLiteral([BSTString("In {\\em "), Identifier("booktitle"), Identifier("*"), BSTString("\\/}"), Identifier("*")]), Identifier("if\$")]), FunctionLiteral([BSTString("In "), Identifier("key"), Identifier("*")]), Identifier("if\$")]),
   FunctionLiteral([BSTString("In "), Identifier("format.crossref.editor"), Identifier("*")]),
   Identifier("if\$"),
   BSTString(" \\cite{"),
   Identifier("*"),
   Identifier("crossref"),
   Identifier("*"),
   BSTString("}"),
   Identifier("*")]],
 ["FUNCTION",
  [Identifier("article")],
  [Identifier("output.bibitem"),
   Identifier("format.authors"),
   BSTString("author"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("format.title"),
   BSTString("title"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("crossref"),
   Identifier("missing\$"),
   FunctionLiteral([Identifier("journal"), Identifier("emphasize"), BSTString("journal"), Identifier("output.check"), Identifier("format.vol.num.pages"), Identifier("output"), Identifier("format.date"), BSTString("year"), Identifier("output.check")]),
   FunctionLiteral([Identifier("format.article.crossref"), Identifier("output.nonnull"), Identifier("format.pages"), Identifier("output")]),
   Identifier("if\$"),
   Identifier("new.block"),
   Identifier("note"),
   Identifier("output"),
   Identifier("fin.entry")]],
 ["FUNCTION",
  [Identifier("book")],
  [Identifier("output.bibitem"),
   Identifier("author"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("format.editors"), BSTString("author and editor"), Identifier("output.check")]),
   FunctionLiteral([Identifier("format.authors"), Identifier("output.nonnull"), Identifier("crossref"), Identifier("missing\$"), FunctionLiteral([BSTString("author and editor"), Identifier("editor"), Identifier("either.or.check")]), QuotedVar("skip\$"), Identifier("if\$")]),
   Identifier("if\$"),
   Identifier("new.block"),
   Identifier("format.btitle"),
   BSTString("title"),
   Identifier("output.check"),
   Identifier("crossref"),
   Identifier("missing\$"),
   FunctionLiteral([Identifier("format.bvolume"), Identifier("output"), Identifier("new.block"), Identifier("format.number.series"), Identifier("output"), Identifier("new.sentence"), Identifier("publisher"), BSTString("publisher"), Identifier("output.check"), Identifier("address"), Identifier("output")]),
   FunctionLiteral([Identifier("new.block"), Identifier("format.book.crossref"), Identifier("output.nonnull")]),
   Identifier("if\$"),
   Identifier("format.edition"),
   Identifier("output"),
   Identifier("format.date"),
   BSTString("year"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("note"),
   Identifier("output"),
   Identifier("fin.entry")]],
 ["FUNCTION",
  [Identifier("booklet")],
  [Identifier("output.bibitem"),
   Identifier("format.authors"),
   Identifier("output"),
   Identifier("new.block"),
   Identifier("format.title"),
   BSTString("title"),
   Identifier("output.check"),
   Identifier("howpublished"),
   Identifier("address"),
   Identifier("new.block.checkb"),
   Identifier("howpublished"),
   Identifier("output"),
   Identifier("address"),
   Identifier("output"),
   Identifier("format.date"),
   Identifier("output"),
   Identifier("new.block"),
   Identifier("note"),
   Identifier("output"),
   Identifier("fin.entry")]],
 ["FUNCTION",
  [Identifier("inbook")],
  [Identifier("output.bibitem"),
   Identifier("author"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("format.editors"), BSTString("author and editor"), Identifier("output.check")]),
   FunctionLiteral([Identifier("format.authors"), Identifier("output.nonnull"), Identifier("crossref"), Identifier("missing\$"), FunctionLiteral([BSTString("author and editor"), Identifier("editor"), Identifier("either.or.check")]), QuotedVar("skip\$"), Identifier("if\$")]),
   Identifier("if\$"),
   Identifier("new.block"),
   Identifier("format.btitle"),
   BSTString("title"),
   Identifier("output.check"),
   Identifier("crossref"),
   Identifier("missing\$"),
   FunctionLiteral([Identifier("format.bvolume"), Identifier("output"), Identifier("format.chapter.pages"), BSTString("chapter and pages"), Identifier("output.check"), Identifier("new.block"), Identifier("format.number.series"), Identifier("output"), Identifier("new.sentence"), Identifier("publisher"), BSTString("publisher"), Identifier("output.check"), Identifier("address"), Identifier("output")]),
   FunctionLiteral([Identifier("format.chapter.pages"), BSTString("chapter and pages"), Identifier("output.check"), Identifier("new.block"), Identifier("format.book.crossref"), Identifier("output.nonnull")]),
   Identifier("if\$"),
   Identifier("format.edition"),
   Identifier("output"),
   Identifier("format.date"),
   BSTString("year"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("note"),
   Identifier("output"),
   Identifier("fin.entry")]],
 ["FUNCTION",
  [Identifier("incollection")],
  [Identifier("output.bibitem"),
   Identifier("format.authors"),
   BSTString("author"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("format.title"),
   BSTString("title"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("crossref"),
   Identifier("missing\$"),
   FunctionLiteral([Identifier("format.in.ed.booktitle"), BSTString("booktitle"), Identifier("output.check"), Identifier("format.bvolume"), Identifier("output"), Identifier("format.number.series"), Identifier("output"), Identifier("format.chapter.pages"), Identifier("output"), Identifier("new.sentence"), Identifier("publisher"), BSTString("publisher"), Identifier("output.check"), Identifier("address"), Identifier("output"), Identifier("format.edition"), Identifier("output"), Identifier("format.date"), BSTString("year"), Identifier("output.check")]),
   FunctionLiteral([Identifier("format.incoll.inproc.crossref"), Identifier("output.nonnull"), Identifier("format.chapter.pages"), Identifier("output")]),
   Identifier("if\$"),
   Identifier("new.block"),
   Identifier("note"),
   Identifier("output"),
   Identifier("fin.entry")]],
 ["FUNCTION",
  [Identifier("inproceedings")],
  [Identifier("output.bibitem"),
   Identifier("format.authors"),
   BSTString("author"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("format.title"),
   BSTString("title"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("crossref"),
   Identifier("missing\$"),
   FunctionLiteral([Identifier("format.in.ed.booktitle"), BSTString("booktitle"), Identifier("output.check"), Identifier("format.bvolume"), Identifier("output"), Identifier("format.number.series"), Identifier("output"), Identifier("format.pages"), Identifier("output"), Identifier("address"), Identifier("empty\$"), FunctionLiteral([Identifier("organization"), Identifier("publisher"), Identifier("new.sentence.checkb"), Identifier("organization"), Identifier("output"), Identifier("publisher"), Identifier("output"), Identifier("format.date"), BSTString("year"), Identifier("output.check")]), FunctionLiteral([Identifier("address"), Identifier("output.nonnull"), Identifier("format.date"), BSTString("year"), Identifier("output.check"), Identifier("new.sentence"), Identifier("organization"), Identifier("output"), Identifier("publisher"), Identifier("output")]), Identifier("if\$")]),
   FunctionLiteral([Identifier("format.incoll.inproc.crossref"), Identifier("output.nonnull"), Identifier("format.pages"), Identifier("output")]),
   Identifier("if\$"),
   Identifier("new.block"),
   Identifier("note"),
   Identifier("output"),
   Identifier("fin.entry")]],
 ["FUNCTION", [Identifier("conference")], [Identifier("inproceedings")]],
 ["FUNCTION",
  [Identifier("manual")],
  [Identifier("output.bibitem"),
   Identifier("author"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("organization"), Identifier("empty\$"), QuotedVar("skip\$"), FunctionLiteral([Identifier("organization"), Identifier("output.nonnull"), Identifier("address"), Identifier("output")]), Identifier("if\$")]),
   FunctionLiteral([Identifier("format.authors"), Identifier("output.nonnull")]),
   Identifier("if\$"),
   Identifier("new.block"),
   Identifier("format.btitle"),
   BSTString("title"),
   Identifier("output.check"),
   Identifier("author"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("organization"), Identifier("empty\$"), FunctionLiteral([Identifier("address"), Identifier("new.block.checka"), Identifier("address"), Identifier("output")]), QuotedVar("skip\$"), Identifier("if\$")]),
   FunctionLiteral([Identifier("organization"), Identifier("address"), Identifier("new.block.checkb"), Identifier("organization"), Identifier("output"), Identifier("address"), Identifier("output")]),
   Identifier("if\$"),
   Identifier("format.edition"),
   Identifier("output"),
   Identifier("format.date"),
   Identifier("output"),
   Identifier("new.block"),
   Identifier("note"),
   Identifier("output"),
   Identifier("fin.entry")]],
 ["FUNCTION",
  [Identifier("mastersthesis")],
  [Identifier("output.bibitem"),
   Identifier("format.authors"),
   BSTString("author"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("format.title"),
   BSTString("title"),
   Identifier("output.check"),
   Identifier("new.block"),
   BSTString("Master's thesis"),
   Identifier("format.thesis.type"),
   Identifier("output.nonnull"),
   Identifier("school"),
   BSTString("school"),
   Identifier("output.check"),
   Identifier("address"),
   Identifier("output"),
   Identifier("format.date"),
   BSTString("year"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("note"),
   Identifier("output"),
   Identifier("fin.entry")]],
 ["FUNCTION",
  [Identifier("misc")],
  [Identifier("output.bibitem"),
   Identifier("format.authors"),
   Identifier("output"),
   Identifier("title"),
   Identifier("howpublished"),
   Identifier("new.block.checkb"),
   Identifier("format.title"),
   Identifier("output"),
   Identifier("howpublished"),
   Identifier("new.block.checka"),
   Identifier("howpublished"),
   Identifier("output"),
   Identifier("format.date"),
   Identifier("output"),
   Identifier("new.block"),
   Identifier("note"),
   Identifier("output"),
   Identifier("fin.entry"),
   Identifier("empty.misc.check")]],
 ["FUNCTION",
  [Identifier("phdthesis")],
  [Identifier("output.bibitem"),
   Identifier("format.authors"),
   BSTString("author"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("format.btitle"),
   BSTString("title"),
   Identifier("output.check"),
   Identifier("new.block"),
   BSTString("PhD thesis"),
   Identifier("format.thesis.type"),
   Identifier("output.nonnull"),
   Identifier("school"),
   BSTString("school"),
   Identifier("output.check"),
   Identifier("address"),
   Identifier("output"),
   Identifier("format.date"),
   BSTString("year"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("note"),
   Identifier("output"),
   Identifier("fin.entry")]],
 ["FUNCTION",
  [Identifier("proceedings")],
  [Identifier("output.bibitem"),
   Identifier("editor"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("organization"), Identifier("output")]),
   FunctionLiteral([Identifier("format.editors"), Identifier("output.nonnull")]),
   Identifier("if\$"),
   Identifier("new.block"),
   Identifier("format.btitle"),
   BSTString("title"),
   Identifier("output.check"),
   Identifier("format.bvolume"),
   Identifier("output"),
   Identifier("format.number.series"),
   Identifier("output"),
   Identifier("address"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("editor"), Identifier("empty\$"), FunctionLiteral([Identifier("publisher"), Identifier("new.sentence.checka")]), FunctionLiteral([Identifier("organization"), Identifier("publisher"), Identifier("new.sentence.checkb"), Identifier("organization"), Identifier("output")]), Identifier("if\$"), Identifier("publisher"), Identifier("output"), Identifier("format.date"), BSTString("year"), Identifier("output.check")]),
   FunctionLiteral([Identifier("address"), Identifier("output.nonnull"), Identifier("format.date"), BSTString("year"), Identifier("output.check"), Identifier("new.sentence"), Identifier("editor"), Identifier("empty\$"), QuotedVar("skip\$"), FunctionLiteral([Identifier("organization"), Identifier("output")]), Identifier("if\$"), Identifier("publisher"), Identifier("output")]),
   Identifier("if\$"),
   Identifier("new.block"),
   Identifier("note"),
   Identifier("output"),
   Identifier("fin.entry")]],
 ["FUNCTION",
  [Identifier("techreport")],
  [Identifier("output.bibitem"),
   Identifier("format.authors"),
   BSTString("author"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("format.title"),
   BSTString("title"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("format.tr.number"),
   Identifier("output.nonnull"),
   Identifier("institution"),
   BSTString("institution"),
   Identifier("output.check"),
   Identifier("address"),
   Identifier("output"),
   Identifier("format.date"),
   BSTString("year"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("note"),
   Identifier("output"),
   Identifier("fin.entry")]],
 ["FUNCTION",
  [Identifier("unpublished")],
  [Identifier("output.bibitem"),
   Identifier("format.authors"),
   BSTString("author"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("format.title"),
   BSTString("title"),
   Identifier("output.check"),
   Identifier("new.block"),
   Identifier("note"),
   BSTString("note"),
   Identifier("output.check"),
   Identifier("format.date"),
   Identifier("output"),
   Identifier("fin.entry")]],
 ["FUNCTION", [Identifier("default.type")], [Identifier("misc")]],
 ["MACRO", [Identifier("jan")], [BSTString("January")]],
 ["MACRO", [Identifier("feb")], [BSTString("February")]],
 ["MACRO", [Identifier("mar")], [BSTString("March")]],
 ["MACRO", [Identifier("apr")], [BSTString("April")]],
 ["MACRO", [Identifier("may")], [BSTString("May")]],
 ["MACRO", [Identifier("jun")], [BSTString("June")]],
 ["MACRO", [Identifier("jul")], [BSTString("July")]],
 ["MACRO", [Identifier("aug")], [BSTString("August")]],
 ["MACRO", [Identifier("sep")], [BSTString("September")]],
 ["MACRO", [Identifier("oct")], [BSTString("October")]],
 ["MACRO", [Identifier("nov")], [BSTString("November")]],
 ["MACRO", [Identifier("dec")], [BSTString("December")]],
 ["MACRO", [Identifier("acmcs")], [BSTString("ACM Computing Surveys")]],
 ["MACRO", [Identifier("acta")], [BSTString("Acta Informatica")]],
 ["MACRO", [Identifier("cacm")], [BSTString("Communications of the ACM")]],
 ["MACRO",
  [Identifier("ibmjrd")],
  [BSTString("IBM Journal of Research and Development")]],
 ["MACRO", [Identifier("ibmsj")], [BSTString("IBM Systems Journal")]],
 ["MACRO",
  [Identifier("ieeese")],
  [BSTString("IEEE Transactions on Software Engineering")]],
 ["MACRO",
  [Identifier("ieeetc")],
  [BSTString("IEEE Transactions on Computers")]],
 ["MACRO",
  [Identifier("ieeetcad")],
  [BSTString("IEEE Transactions on Computer-Aided Design of Integrated Circuits")]],
 ["MACRO", [Identifier("ipl")], [BSTString("Information Processing Letters")]],
 ["MACRO", [Identifier("jacm")], [BSTString("Journal of the ACM")]],
 ["MACRO",
  [Identifier("jcss")],
  [BSTString("Journal of Computer and System Sciences")]],
 ["MACRO",
  [Identifier("scp")],
  [BSTString("Science of Computer Programming")]],
 ["MACRO", [Identifier("sicomp")], [BSTString("SIAM Journal on Computing")]],
 ["MACRO",
  [Identifier("tocs")],
  [BSTString("ACM Transactions on Computer Systems")]],
 ["MACRO",
  [Identifier("tods")],
  [BSTString("ACM Transactions on Database Systems")]],
 ["MACRO", [Identifier("tog")], [BSTString("ACM Transactions on Graphics")]],
 ["MACRO",
  [Identifier("toms")],
  [BSTString("ACM Transactions on Mathematical Software")]],
 ["MACRO",
  [Identifier("toois")],
  [BSTString("ACM Transactions on Office Information Systems")]],
 ["MACRO",
  [Identifier("toplas")],
  [BSTString("ACM Transactions on Programming Languages and Systems")]],
 ["MACRO", [Identifier("tcs")], [BSTString("Theoretical Computer Science")]],
 ["READ"],
 ["FUNCTION",
  [Identifier("sortify")],
  [Identifier("purify\$"), BSTString("l"), Identifier("change.case\$")]],
 ["INTEGERS", [Identifier("len")]],
 ["FUNCTION",
  [Identifier("chop.word")],
  [QuotedVar("s"),
   Identifier(":="),
   QuotedVar("len"),
   Identifier(":="),
   Identifier("s"),
   BSTInteger(1),
   Identifier("len"),
   Identifier("substring\$"),
   Identifier("="),
   FunctionLiteral([Identifier("s"), Identifier("len"), BSTInteger(1), Identifier("+"), Identifier("global.max\$"), Identifier("substring\$")]),
   QuotedVar("s"),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("sort.format.names")],
  [QuotedVar("s"),
   Identifier(":="),
   BSTInteger(1),
   QuotedVar("nameptr"),
   Identifier(":="),
   BSTString(""),
   Identifier("s"),
   Identifier("num.names\$"),
   QuotedVar("numnames"),
   Identifier(":="),
   Identifier("numnames"),
   QuotedVar("namesleft"),
   Identifier(":="),
   FunctionLiteral([Identifier("namesleft"), BSTInteger(0), Identifier(">")]),
   FunctionLiteral([Identifier("nameptr"), BSTInteger(1), Identifier(">"), FunctionLiteral([BSTString("   "), Identifier("*")]), QuotedVar("skip\$"), Identifier("if\$"), Identifier("s"), Identifier("nameptr"), BSTString("{vv{ } }{ll{ }}{  ff{ }}{  jj{ }}"), Identifier("format.name\$"), QuotedVar("t"), Identifier(":="), Identifier("nameptr"), Identifier("numnames"), Identifier("="), Identifier("t"), BSTString("others"), Identifier("="), Identifier("and"), FunctionLiteral([BSTString("et al"), Identifier("*")]), FunctionLiteral([Identifier("t"), Identifier("sortify"), Identifier("*")]), Identifier("if\$"), Identifier("nameptr"), BSTInteger(1), Identifier("+"), QuotedVar("nameptr"), Identifier(":="), Identifier("namesleft"), BSTInteger(1), Identifier("-"), QuotedVar("namesleft"), Identifier(":=")]),
   Identifier("while\$")]],
 ["FUNCTION",
  [Identifier("sort.format.title")],
  [QuotedVar("t"),
   Identifier(":="),
   BSTString("A "),
   BSTInteger(2),
   BSTString("An "),
   BSTInteger(3),
   BSTString("The "),
   BSTInteger(4),
   Identifier("t"),
   Identifier("chop.word"),
   Identifier("chop.word"),
   Identifier("chop.word"),
   Identifier("sortify"),
   BSTInteger(1),
   Identifier("global.max\$"),
   Identifier("substring\$")]],
 ["FUNCTION",
  [Identifier("author.sort")],
  [Identifier("author"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("key"), Identifier("empty\$"), FunctionLiteral([BSTString("to sort, need author or key in "), Identifier("cite\$"), Identifier("*"), Identifier("warning\$"), BSTString("")]), FunctionLiteral([Identifier("key"), Identifier("sortify")]), Identifier("if\$")]),
   FunctionLiteral([Identifier("author"), Identifier("sort.format.names")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("author.editor.sort")],
  [Identifier("author"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("editor"), Identifier("empty\$"), FunctionLiteral([Identifier("key"), Identifier("empty\$"), FunctionLiteral([BSTString("to sort, need author, editor, or key in "), Identifier("cite\$"), Identifier("*"), Identifier("warning\$"), BSTString("")]), FunctionLiteral([Identifier("key"), Identifier("sortify")]), Identifier("if\$")]), FunctionLiteral([Identifier("editor"), Identifier("sort.format.names")]), Identifier("if\$")]),
   FunctionLiteral([Identifier("author"), Identifier("sort.format.names")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("author.organization.sort")],
  [Identifier("author"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("organization"), Identifier("empty\$"), FunctionLiteral([Identifier("key"), Identifier("empty\$"), FunctionLiteral([BSTString("to sort, need author, organization, or key in "), Identifier("cite\$"), Identifier("*"), Identifier("warning\$"), BSTString("")]), FunctionLiteral([Identifier("key"), Identifier("sortify")]), Identifier("if\$")]), FunctionLiteral([BSTString("The "), BSTInteger(4), Identifier("organization"), Identifier("chop.word"), Identifier("sortify")]), Identifier("if\$")]),
   FunctionLiteral([Identifier("author"), Identifier("sort.format.names")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("editor.organization.sort")],
  [Identifier("editor"),
   Identifier("empty\$"),
   FunctionLiteral([Identifier("organization"), Identifier("empty\$"), FunctionLiteral([Identifier("key"), Identifier("empty\$"), FunctionLiteral([BSTString("to sort, need editor, organization, or key in "), Identifier("cite\$"), Identifier("*"), Identifier("warning\$"), BSTString("")]), FunctionLiteral([Identifier("key"), Identifier("sortify")]), Identifier("if\$")]), FunctionLiteral([BSTString("The "), BSTInteger(4), Identifier("organization"), Identifier("chop.word"), Identifier("sortify")]), Identifier("if\$")]),
   FunctionLiteral([Identifier("editor"), Identifier("sort.format.names")]),
   Identifier("if\$")]],
 ["FUNCTION",
  [Identifier("presort")],
  [Identifier("type\$"),
   BSTString("book"),
   Identifier("="),
   Identifier("type\$"),
   BSTString("inbook"),
   Identifier("="),
   Identifier("or"),
   QuotedVar("author.editor.sort"),
   FunctionLiteral([Identifier("type\$"), BSTString("proceedings"), Identifier("="), QuotedVar("editor.organization.sort"), FunctionLiteral([Identifier("type\$"), BSTString("manual"), Identifier("="), QuotedVar("author.organization.sort"), QuotedVar("author.sort"), Identifier("if\$")]), Identifier("if\$")]),
   Identifier("if\$"),
   BSTString("    "),
   Identifier("*"),
   Identifier("year"),
   Identifier("field.or.null"),
   Identifier("sortify"),
   Identifier("*"),
   BSTString("    "),
   Identifier("*"),
   Identifier("title"),
   Identifier("field.or.null"),
   Identifier("sort.format.title"),
   Identifier("*"),
   BSTInteger(1),
   Identifier("entry.max\$"),
   Identifier("substring\$"),
   QuotedVar("sort.key\$"),
   Identifier(":=")]],
 ["ITERATE", [Identifier("presort")]],
 ["SORT"],
 ["STRINGS", [Identifier("longest.label")]],
 ["INTEGERS",
  [Identifier("number.label"), Identifier("longest.label.width")]],
 ["FUNCTION",
  [Identifier("initialize.longest.label")],
  [BSTString(""),
   QuotedVar("longest.label"),
   Identifier(":="),
   BSTInteger(1),
   QuotedVar("number.label"),
   Identifier(":="),
   BSTInteger(0),
   QuotedVar("longest.label.width"),
   Identifier(":=")]],
 ["FUNCTION",
  [Identifier("longest.label.pass")],
  [Identifier("number.label"),
   Identifier("int.to.str\$"),
   QuotedVar("label"),
   Identifier(":="),
   Identifier("number.label"),
   BSTInteger(1),
   Identifier("+"),
   QuotedVar("number.label"),
   Identifier(":="),
   Identifier("label"),
   Identifier("width\$"),
   Identifier("longest.label.width"),
   Identifier(">"),
   FunctionLiteral([Identifier("label"), QuotedVar("longest.label"), Identifier(":="), Identifier("label"), Identifier("width\$"), QuotedVar("longest.label.width"), Identifier(":=")]),
   QuotedVar("skip\$"),
   Identifier("if\$")]],
 ["EXECUTE", [Identifier("initialize.longest.label")]],
 ["ITERATE", [Identifier("longest.label.pass")]],
 ["FUNCTION",
  [Identifier("begin.bib")],
  [Identifier("preamble\$"),
   Identifier("empty\$"),
   QuotedVar("skip\$"),
   FunctionLiteral([Identifier("preamble\$"), Identifier("write\$"), Identifier("newline\$")]),
   Identifier("if\$"),
   BSTString("\\begin{thebibliography}{"),
   Identifier("longest.label"),
   Identifier("*"),
   BSTString("}"),
   Identifier("*"),
   Identifier("write\$"),
   Identifier("newline\$")]],
 ["EXECUTE", [Identifier("begin.bib")]],
 ["EXECUTE", [Identifier("init.state.consts")]],
 ["ITERATE", [Identifier("call.type\$")]],
 ["FUNCTION",
  [Identifier("end.bib")],
  [Identifier("newline\$"),
   BSTString("\\end{thebibliography}"),
   Identifier("write\$"),
   Identifier("newline\$")]],
 ["EXECUTE", [Identifier("end.bib")]]]
